version: '3.8'

services:
  mongodb:
    image: mongo
    volumes:
      # Named volume to persist database
      - data:/data/db
    env_file:
      - ./env/mongodb.env
  backend:
    build:
      context: ./backend
      dockerfile: backend.dockerfile
    ports:
      - '8000:8000'
    env_file:
      - ./env/backend.env
    depends_on:
      - mongodb
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    volumes:
      # Bind mount volume for live frontend updates while developing
      - ./frontend/src:/client/src
    stdin_open: true
    tty: true
    depends_on:
      - backend

# Note only named volumes need to be listed here for persistance.
volumes:
  data: